// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import CallToAction from './CallToAction';
import Faqs from './Faqs';
import FooterLinks from './FooterLinks';
import Hero from './Hero';
import Logos from './Logos';
import NavLinks from './NavLinks';
import Process from './Process';
import Services from './Services';
import Work from './Work';

export {
	About,
	CallToAction,
	Faqs,
	FooterLinks,
	Hero,
	Logos,
	NavLinks,
	Process,
	Services,
	Work,
};

export const components = {
	about: About,
	call_to_action: CallToAction,
	faqs: Faqs,
	footer_links: FooterLinks,
	hero: Hero,
	logos: Logos,
	nav_links: NavLinks,
	process: Process,
	services: Services,
	work: Work,
};
