// This file is generated by Slice Machine. Update with care!

import About from './About';
import CallToAction from './CallToAction';
import FooterLinks from './FooterLinks';
import Hero from './Hero';
import NavLinks from './NavLinks';
import Services from './Services';

export {
	About,
	CallToAction,
	FooterLinks,
	Hero,
	NavLinks,
	Services,
};

export const components = {
	about: About,
	call_to_action: CallToAction,
	footer_links: FooterLinks,
	hero: Hero,
	nav_links: NavLinks,
	services: Services,
};
