// Code generated by Slice Machine. DO NOT EDIT.

import Blockquote from './Blockquote';
import Image from './Image';
import Text from './Text';

export {
	Blockquote,
	Image,
	Text,
};

export const components = {
	blockquote: Blockquote,
	image: Image,
	text: Text,
};
